### ISSUE TITLE
S3 adapter - The bucket you are attempting to access must be addressed using the specified endpoint.

### ISSUE THREAD

**Issue by bedge** [scttnlsn/dandelion#105]
Does one need to specify a region if not using the default?

Here's my config:

```
adapter: s3
bucket_name: xxx-xxx-xxx-xxx
access_key_id:ID
secret_access_key: SECRET

exclude:
    - .gitignore
    - dandelion.yml
```

Attempting to deploy shows:

```
%> dandelion deploy
Connecting to s3:/XXXXXXXXXXXXXXXXXXX@xxx-xxx-xxx-xxx/
Digest::Digest is deprecated; use Digest
Digest::Digest is deprecated; use Digest
/usr/local/lib/ruby/gems/2.1.0/gems/aws-s3-0.6.3/lib/aws/s3/error.rb:38:in `raise': The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. (AWS::S3::PermanentRedirect)
        from /usr/local/lib/ruby/gems/2.1.0/gems/aws-s3-0.6.3/lib/aws/s3/base.rb:72:in `request'
        from /usr/local/lib/ruby/gems/2.1.0/gems/aws-s3-0.6.3/lib/aws/s3/base.rb:88:in `get'
        from /usr/local/lib/ruby/gems/2.1.0/gems/aws-s3-0.6.3/lib/aws/s3/object.rb:134:in `value'
        from /usr/local/lib/ruby/gems/2.1.0/gems/dandelion-0.4.6/lib/dandelion/adapter/s3.rb:17:in `read'
        from /usr/local/lib/ruby/gems/2.1.0/gems/dandelion-0.4.6/lib/dandelion/workspace.rb:73:in `remote_sha'
        from /usr/local/lib/ruby/gems/2.1.0/gems/dandelion-0.4.6/lib/dandelion/workspace.rb:33:in `remote_commit'
        from /usr/local/lib/ruby/gems/2.1.0/gems/dandelion-0.4.6/lib/dandelion/command/deploy.rb:25:in `execute!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/dandelion-0.4.6/lib/dandelion/cli.rb:69:in `execute!'
        from /usr/local/lib/ruby/gems/2.1.0/gems/dandelion-0.4.6/bin/dandelion:8:in `<top (required)>'
        from /usr/local/bin/dandelion:23:in `load'
        from /usr/local/bin/dandelion:23:in `<main>'
```

I know the bucket and creds are correct as I can use aws cli to access it:

```
aws s3 ls xxx-xxx-xxx-xxx
                           PRE data/
```

**Comment by StudioLE** [comment]
I also found this error and the message isn't descriptive enough to figure it out. Adding `host` as a required attribute of the s3 adapter and a link to the [s3 endpoints list](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) in the README could help other people out.

**Comment by scttnlsn** [comment]
Thanks @StudioLE,  updated here: https://github.com/scttnlsn/dandelion/commit/9987010c77a05fa2fd96cddb823a523825771d29
