### ISSUE TITLE
Mac OSX Yosemite: Error on deploy and status (FTP)

### ISSUE THREAD

**Issue by ferkosuska** [scttnlsn/dandelion#127]
i have a problem with connection to ftp server, if there is a path specified in the config file

this is my configuration dandelion.yml:
adapter: ftp
host: p259158.mittwaldserver.info
username: xxxxxx
password: xxxxxx
path: html/wordpress

dandelion status
Connecting to ftp://p259158@p259158.mittwaldserver.info/html/wordpress
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:324:in `getresp': 425 Failed to establish connection. (Net::FTPTempError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:351:in `block in sendcmd'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:349:in `sendcmd'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:428:in `transfercmd'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:487:in `block (2 levels) in retrbinary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:199:in `with_binary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:485:in `block in retrbinary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:484:in `retrbinary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/ftp.rb:617:in `getbinaryfile'
	from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.10/lib/dandelion/adapter/ftp.rb:22:in `read'
	from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.10/lib/dandelion/workspace.rb:74:in `remote_sha'
	from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.10/lib/dandelion/workspace.rb:33:in `remote_commit'
	from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.10/lib/dandelion/command/status.rb:16:in `execute!'
	from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.10/lib/dandelion/cli.rb:73:in `execute!'
	from /Library/Ruby/Gems/2.0.0/gems/dandelion-0.4.10/bin/dandelion:8:in `<top (required)>'
	from /usr/bin/dandelion:23:in `load'
	from /usr/bin/dandelion:23:in `<main>'

=======
if i remove the path everything works:

dandelion status
Connecting to ftp://p259158@p259158.mittwaldserver.info/
Remote revision:      ---
Local HEAD revision:  8e3a15b9ad33de60be7fa485b91214cc750326f1

**Comment by ferkosuska** [comment]
i have added following line to dandelion.yml and my problem is solved:
passive: true
