### ISSUE TITLE
Exception thrown when `auth_tls` is `nil` or `false`

### ISSUE THREAD

**Issue by chrisdpeters** [scttnlsn/dandelion#142]
Example config:
```yml
adapter: ftps
host: example.com
username: myusername
password: verysecurepassw0rd
path: 
```
Stack trace:
```
$ dandelion deploy --dry-run
/.rvm/gems/ruby-2.2.3/gems/double-bag-ftps-0.1.2/lib/double_bag_ftps.rb:64:in `+': no implicit conversion of nil into String (TypeError)
	from /.rvm/gems/ruby-2.2.3/gems/double-bag-ftps-0.1.2/lib/double_bag_ftps.rb:64:in `block in login'
	from /.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /.rvm/gems/ruby-2.2.3/gems/double-bag-ftps-0.1.2/lib/double_bag_ftps.rb:63:in `login'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/adapter/ftps.rb:30:in `ftp_client'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/adapter/ftp.rb:17:in `initialize'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/adapter/ftps.rb:18:in `initialize'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/adapter.rb:24:in `new'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/adapter.rb:24:in `create_adapter'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/cli.rb:21:in `adapter'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/cli.rb:37:in `workspace'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/lib/dandelion/cli.rb:69:in `execute!'
	from /.rvm/gems/ruby-2.2.3/gems/dandelion-0.4.14/bin/dandelion:8:in `<top (required)>'
	from /.rvm/gems/ruby-2.2.3/bin/dandelion:23:in `load'
	from /.rvm/gems/ruby-2.2.3/bin/dandelion:23:in `<main>'
	from /.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```
I also tried adding `insecure: true` to no avail.

Unfortunately, we need to run this without TLS verification for now (though I wish I could wave a magic wand and make it better, it is out of my control...).

It looks like double-bag-ftps doesn't like it when `nil` is passed in as the `auth` argument to [`login`](https://github.com/bnix/double-bag-ftps/blob/master/lib/double_bag_ftps.rb#L61).

**Comment by scttnlsn** [comment]
Can you try adding `auth_tls: true` to your `dandelion.yml`.  If that works we should probably make it the default.

**Comment by chrisdpeters** [comment]
I get a different error complaining about the certificate, so that works as expected.

**Comment by chrisdpeters** [comment]
Your idea sounds like a reasonable default, by the way. I was just trying to get it to work with it set to false.

**Comment by scttnlsn** [comment]
I think the problem is just that the FTPS adapter is passing `nil` when `auth_tls` is `false`.  What's another valid value for the `auth` argument to `login`?

**Comment by chrisdpeters** [comment]
It looks like the more common values are `TLS` and `SSL`. `TLS-C` appears to be another less-common possibility. Probably neither would be helpful in my case.

I should have my boss set up the FTPS again with the bad setup and see what the specific error is for `auth_tls: true` to see if that's something that Dandelion can work around.

**Comment by chrisdpeters** [comment]
P. S. I tried skimming through the FTPS spec and couldn't quickly find any more info about `AUTH`.

The Wikipedia article does list some info:
https://en.wikipedia.org/wiki/FTPS
