### ISSUE TITLE
`+': no implicit conversion of Fixnum into String (TypeError)

### ISSUE THREAD

**Issue by xavierartot** [scttnlsn/dandelion#152]
Hi,
I write dandelion deploy and I got this:
```
/usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/ftp.rb:466:in `+': no implicit conversion of Fixnum into String (TypeError)
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/ftp.rb:466:in `block in login'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /usr/local/Cellar/ruby/2.2.2/lib/ruby/2.2.0/net/ftp.rb:462:in `login'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter/ftp.rb:57:in `ftp_client'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter/ftp.rb:17:in `initialize'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter.rb:24:in `new'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/adapter.rb:24:in `create_adapter'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/cli.rb:21:in `adapter'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/cli.rb:37:in `workspace'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/lib/dandelion/cli.rb:69:in `execute!'
	from /usr/local/lib/ruby/gems/2.2.0/gems/dandelion-0.4.16/bin/dandelion:8:in `<top (required)>'
	from /usr/local/bin/dandelion:23:in `load'
	from /usr/local/bin/dandelion:23:in `<main>'
```

**Comment by scttnlsn** [comment]
Could you explain more about your setup and how it may or may not relate to the other issue you posted (https://github.com/scttnlsn/dandelion/issues/150)?

**Comment by xavierartot** [comment]
That true, I had a server problem with the password, sorry.
