### ISSUE TITLE
Not working with ruby 2.5.0 on deploy using sftp

### ISSUE THREAD

**Issue by allaire** [scttnlsn/dandelion#165]
When I try to deploy using sftp (dandelion status is OK), I keep getting this error:

```
Remote revision:    9bca529835027383ff819301b78976b35b12374f
Deploying revision: 20c784721e2bf39dad36887587982ddeb840b60f
Traceback (most recent call last):
	15: from /Users/allaire/.rbenv/versions/2.5.0/bin/dandelion:23:in `<main>'
	14: from /Users/allaire/.rbenv/versions/2.5.0/bin/dandelion:23:in `load'
	13: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/bin/dandelion:8:in `<top (required)>'
	12: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/cli.rb:73:in `execute!'
	11: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/command/deploy.rb:30:in `execute!'
	10: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/command/deploy.rb:51:in `deploy_changeset!'
	 9: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/changeset.rb:16:in `empty?'
	 8: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/changeset.rb:12:in `diff'
	 7: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/changeset.rb:12:in `new'
	 6: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/diff.rb:20:in `initialize'
	 5: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/diff.rb:20:in `new'
	 4: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/dandelion-0.5.2/lib/dandelion/diff.rb:29:in `initialize'
	 3: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rugged-0.26.0/lib/rugged/diff.rb:22:in `deltas'
	 2: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rugged-0.26.0/lib/rugged/diff.rb:22:in `to_a'
	 1: from /Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rugged-0.26.0/lib/rugged/diff.rb:22:in `each'
/Users/allaire/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rugged-0.26.0/lib/rugged/diff.rb:22:in `each_delta': wrong number of arguments (given 6, expected 0) (ArgumentError)
```

I tried previous versions of dandelion and it's not working as well. My setup used to work previously, and I haven't changed my configuration. I'm using `ruby 2.5.0p0` if it matters

Thanks for your time!

**Comment by allaire** [comment]
Confirmed that it works with ruby `2.4.3`
