### ISSUE TITLE
Net::SFTP::StatusException

### ISSUE THREAD

**Issue by peterolle** [scttnlsn/dandelion#173]
Deploying a theme in one of my repositories I get this:

`
Remote revision:    ba4c8f73e1
Deploying revision: 0345d1a55eea64
Deploying changes...
Writing file:  theme/config-layerslider/LayerSlider/static/minicolors/jquery.minicolors.png
Traceback (most recent call last):
	36: from /usr/local/bin/dandelion:23:in `<main>'
	35: from /usr/local/bin/dandelion:23:in `load'
	34: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/bin/dandelion:8:in `<top (required)>'
	33: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/cli.rb:73:in `execute!'
	32: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/command/deploy.rb:30:in `execute!'
	31: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	30: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	29: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/changeset.rb:20:in `each'
	28: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `each'
	27: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/diff.rb:43:in `each'
	26: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/diff.rb:43:in `each'
	25: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/diff.rb:43:in `block in each'
	24: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/changeset.rb:32:in `block in each'
	23: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
	22: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/deployer.rb:49:in `deploy_change!'
	21: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/adapter/sftp.rb:38:in `write'
	20: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/utils.rb:9:in `temp'
	19: from /Library/Ruby/Gems/2.6.0/gems/dandelion-0.5.4/lib/dandelion/adapter/sftp.rb:40:in `block in write'
	18: from /Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
	17: from /Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
	16: from /Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
	15: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `loop'
	14: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `loop'
	13: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:181:in `block in loop'
	12: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:228:in `process'
	11: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:29:in `process'
	10: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:101:in `ev_preprocess'
	 9: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/event_loop.rb:101:in `each'
	 8: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:250:in `ev_preprocess'
	 7: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:540:in `each_channel'
	 6: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:540:in `each'
	 5: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/session.rb:250:in `block in ev_preprocess'
	 4: from /Library/Ruby/Gems/2.6.0/gems/net-ssh-5.2.0/lib/net/ssh/connection/channel.rb:323:in `process'
	 3: from /Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:911:in `when_channel_polled'
	 2: from /Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:948:in `dispatch_request'
	 1: from /Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/request.rb:87:in `respond_to'
/Library/Ruby/Gems/2.6.0/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:339:in `on_write': Net::SFTP::StatusException write public_html/wp-content/themes/theme/config-layerslider/LayerSlider/static/minicolors/jquery.minicolors.png (4, "failure") (Net::SFTP::StatusException)
`

Before that one I was able to deploy without any problems to another domain.

What can be the problem?

**Comment by peterolle** [comment]
For anyone running into this, it was disk space for me.

Cheers.
