### ISSUE TITLE
Error Deploying

### ISSUE THREAD

**Issue by DustinHartzler** [scttnlsn/dandelion#76]
When I run 'dandelion deploy' or 'dandelion ~~config~~ status' I get the following error:

```
/Users/DMoney/.rvm/gems/ruby-1.9.2-p320/gems/dandelion-0.4.2/lib/dandelion/cli.rb:38:in `command_class': undefined method `to_sym' for nil:NilClass (NoMethodError)
    from /Users/DMoney/.rvm/gems/ruby-1.9.2-p320/gems/dandelion-0.4.2/lib/dandelion/cli.rb:60:in `execute!'
    from /Users/DMoney/.rvm/gems/ruby-1.9.2-p320/gems/dandelion-0.4.2/bin/dandelion:8:in `<top (required)>'
    from /Users/DMoney/.rvm/gems/ruby-1.9.2-p320/bin/dandelion:23:in `load'
    from /Users/DMoney/.rvm/gems/ruby-1.9.2-p320/bin/dandelion:23:in `<main>'
    from /Users/DMoney/.rvm/gems/ruby-1.9.2-p320/bin/ruby_executable_hooks:15:in `eval'
    from /Users/DMoney/.rvm/gems/ruby-1.9.2-p320/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jpgdcl** [comment]
Hi

I'm getting a similar issue:

```
Writing file:  statamic/vendor/lesaff/useragent
/Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/tree.rb:43:in `content': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/tree.rb:18:in `data'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/tree.rb:57:in `symlink_content'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/tree.rb:44:in `content'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/tree.rb:18:in `data'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/changeset.rb:27:in `block (2 levels) in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/change.rb:12:in `call'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/change.rb:12:in `data'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/deployer.rb:49:in `deploy_change!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/changeset.rb:28:in `block in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/diff.rb:58:in `block in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/diff.rb:57:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/diff.rb:57:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/changeset.rb:20:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/command/deploy.rb:30:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:73:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/bin/dandelion:8:in `<top (required)>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `load'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `<main>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Js-MBP:humanjpg.dev J$ dandelion status
/Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:116:in `exists?': no implicit conversion of nil into String (TypeError)
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:116:in `validate!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:65:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/bin/dandelion:8:in `<top (required)>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `load'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `<main>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Js-MBP:humanjpg.dev J$ dandelion status
/Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:116:in `exists?': no implicit conversion of nil into String (TypeError)
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:116:in `validate!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:65:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/bin/dandelion:8:in `<top (required)>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `load'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `<main>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

I got the above when running `dandelion status` in the same Terminal tab.

I tried to deploy again and got the following error:

```
/Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/buffered_io.rb:65:in `recv': Network is down - recvfrom(2) (Errno::ENETDOWN)
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/buffered_io.rb:65:in `fill'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:237:in `block in postprocess'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:233:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:233:in `postprocess'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:212:in `process'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `block in loop'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-ssh-2.9.2/lib/net/ssh/connection/session.rb:170:in `loop'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:802:in `loop'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/operations/upload.rb:203:in `wait'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/net-sftp-2.1.2/lib/net/sftp/session.rb:103:in `upload!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/adapter/sftp.rb:35:in `block in write'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/utils.rb:9:in `temp'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/adapter/sftp.rb:33:in `write'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/deployer.rb:49:in `deploy_change!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/changeset.rb:28:in `block in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/diff.rb:58:in `block in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/diff.rb:57:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/diff.rb:57:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/changeset.rb:20:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/command/deploy.rb:30:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/lib/dandelion/cli.rb:73:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.14/bin/dandelion:8:in `<top (required)>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `load'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `<main>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by scttnlsn** [comment]
@jpgdcl Could you update Dandelion and try again?  This should be fixed in v0.4.16 (https://github.com/scttnlsn/dandelion/commit/b833f0eae2a4ac81a08f86dbbb301febb4ca2394).

**Comment by jpgdcl** [comment]
I updated, tried to deploy again but received the following error (below). The file is from a Statamic add-on (https://github.com/lesaff/statamic-useragent), which I've actually removed in a subsequent commit. (I've had other problems with it, trying update it via composer as I had to manually add it to the CMS's `composer.json` file - Sorry, this is all way over my head, so no idea what I'm doing here!)

Could it be something to do with the actual file? I thought Dandelion just respects git and deploys whatever's there regardless of the content of the file? 

Going to try and change the name of the revision file and redeploy from scratch. Takes hours to deploy though as the folder is ~ 300mb. 

```
Writing file:  statamic/vendor/lesaff/useragent
/Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/tree.rb:43:in `content': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/tree.rb:18:in `data'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/tree.rb:57:in `symlink_content'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/tree.rb:44:in `content'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/tree.rb:18:in `data'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/changeset.rb:27:in `block (2 levels) in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/change.rb:12:in `call'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/change.rb:12:in `data'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/deployer.rb:49:in `deploy_change!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/deployer.rb:13:in `block in deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/changeset.rb:28:in `block in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/diff.rb:58:in `block in each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/diff.rb:57:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/diff.rb:57:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/changeset.rb:20:in `each'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/deployer.rb:9:in `deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/command/deploy.rb:55:in `deploy_changeset!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/command/deploy.rb:30:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/lib/dandelion/cli.rb:73:in `execute!'
	from /Users/J/.rvm/gems/ruby-2.2.1/gems/dandelion-0.4.16/bin/dandelion:8:in `<top (required)>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `load'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/dandelion:23:in `<main>'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/J/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by scttnlsn** [comment]
Is `statamic/vendor/lesaff/useragent` a symlink?  Where is it pointing?
